#! /bin/sh
# /etc/init.d/front
### BEGIN INIT INFO
# Provides:          front
# Required-Start:    
# Required-Stop:     
# Should-Start:      
# Should-Stop:       
# X-Start-Before:    
# X-Stop-After:      
# Default-Start:     2 3 4 5
# Default-Stop:      1
### END INIT INFO

# Some things that run always
sleep 1
# Carry out specific functions when asked to by the system
case "$1" in
  start)
    sudo python /root/front.py &
    ;;
  stop)
    ;;
  *)
    echo "Usage: /etc/init.d/front {start|stop}"
    exit 1
    ;;
esac

exit 0
